select-configuration:
  title: Welcome to Select
  menus:
    - group: 회원
      name: 고객 관리
      path: users
      placement: menu-only
      redirect: users/active
    
    - group: 회원
      name: 최근가입자 목록
      path: users/active
      placement: tab-only

    - group: 회원
      name: 휴면회원 목록
      path: users/dormant
      placement: tab-only

    - group: 회원
      name: 마케팅 수신동의
      path: users/promotion
      placement: tab-only
    
    - group: 기타메뉴
      name: 공식 문서 
      path: https://docs.selectfromuser.com
      target: _blank

    - group: 기타메뉴
      name: 클라우드 이용
      path: https://selectfromuser.com
      target: _blank

  access-control:
    
  users:
    - id: admin
      pw: YWRtaW4=
      roles:
  
  integrations:
    google-sso:
      enabled: false
      restrict-domain: 
    google-spreadsheets:
      restrict-domain: 
  
  pages:
    - path: users/active
      blocks: 
        - type: markdown
          content: >
            ## 7일 가입자 조회
        
    - path: users/dormant
      blocks:
        - type: markdown
          content: >
            ## 휴면회원 조회
        
    - path: users/promotion
      blocks:
        - type: markdown
          content: >
            ## 동의/미동의 조회
        
  resources:
    # - key: mysql
    #   type: mysql
    #   host: YOUR_HOST.ap-northeast-2.rds.amazonaws.com
    #   port: 3306
    #   username: (계정이름)
    #   password: (base64 인코딩된 계정 비밀번호)
    #   database: (데이터베이스이름)
    #   timezone: '+00:00'
    #   extra:
    #     charset: utf8mb4_general_ci

redis:
  master:
    host: 127.0.0.1
    port: 6379
    db: 0

web: 
  base_url: http://localhost:9400

secret:
  access_token: SECRET

policy:
  session_expire: 48300

google:
  client_id: 
  redirect_uri: 
  client_secret: 

google_sheet:
  client_id: 
  redirect_uri: 
  client_secret: 
